import React from 'react';
import {
  Printer,
  Download,
  ArrowLeft,
  Bot,
  CheckCircle2,
  AlertTriangle,
  TrendingUp,
  Target,
  Calendar,
} from 'lucide-react';
import { CATEGORIES_CONFIG } from '../data/categories';
import {
  ExpenseCategory,
  ExpenseItem,
  FinancialAnalysis,
  FinancialPersona,
  FinancialSnapshot,
  IncomeItem,
} from '../types/finance';
import { formatCurrency, formatDate } from '../utils/financeCalculations';

interface MonthlyReportViewProps {
  snapshot: FinancialSnapshot;
  persona: FinancialPersona;
  currency: string;
  analysis: FinancialAnalysis;
  expenses: ExpenseItem[];
  incomes: IncomeItem[];
  onBack: () => void;
}

export const MonthlyReportView: React.FC<MonthlyReportViewProps> = ({
  snapshot,
  persona,
  currency,
  analysis,
  expenses,
  incomes,
  onBack,
}) => {
  const handlePrint = () => {
    window.print();
  };

  const handleExportCSV = () => {
    const headers = ['Type', 'Date', 'Title/Source', 'Category', 'Amount'];
    const expenseRows = expenses.map((e) => [
      'Expense',
      e.date,
      `"${e.title.replace(/"/g, '""')}"`,
      e.category,
      e.amount.toFixed(2),
    ]);
    const incomeRows = incomes.map((i) => [
      'Income',
      i.date,
      `"${i.source.replace(/"/g, '""')}"`,
      'Income',
      i.amount.toFixed(2),
    ]);

    const csvContent =
      'data:text/csv;charset=utf-8,' +
      [headers.join(','), ...incomeRows.map((r) => r.join(',')), ...expenseRows.map((r) => r.join(','))].join(
        '\n'
      );

    const encodedUri = encodeURI(csvContent);
    const link = document.createElement('a');
    link.setAttribute('href', encodedUri);
    link.setAttribute('download', `financial-report-${persona.id}-sep2026.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  return (
    <div className="max-w-4xl mx-auto space-y-6">
      {/* Top action bar (hidden during print) */}
      <div className="flex items-center justify-between print:hidden">
        <button
          onClick={onBack}
          className="flex items-center space-x-1.5 text-xs font-semibold text-slate-600 hover:text-slate-900 bg-white px-3 py-2 rounded-xl border border-slate-200 shadow-xs cursor-pointer"
        >
          <ArrowLeft className="w-4 h-4" />
          <span>Back to Dashboard</span>
        </button>

        <div className="flex items-center space-x-2">
          <button
            onClick={handleExportCSV}
            className="flex items-center space-x-1.5 text-xs font-semibold text-slate-700 bg-white hover:bg-slate-50 px-3.5 py-2 rounded-xl border border-slate-200 shadow-xs cursor-pointer"
          >
            <Download className="w-4 h-4 text-slate-500" />
            <span>Export CSV</span>
          </button>
          <button
            onClick={handlePrint}
            className="flex items-center space-x-1.5 text-xs font-bold text-white bg-slate-900 hover:bg-slate-800 px-4 py-2 rounded-xl shadow-xs cursor-pointer"
          >
            <Printer className="w-4 h-4" />
            <span>Print / Save PDF</span>
          </button>
        </div>
      </div>

      {/* Main Report Document Container */}
      <div className="bg-white rounded-3xl p-8 sm:p-10 border border-slate-200 shadow-sm print:shadow-none print:border-none print:p-0 space-y-8">
        {/* Report Header */}
        <div className="flex flex-col sm:flex-row sm:items-start justify-between pb-6 border-b border-slate-200 gap-4">
          <div>
            <div className="flex items-center space-x-2">
              <span className="w-7 h-7 rounded-lg bg-emerald-600 text-white flex items-center justify-center font-bold text-sm">
                PF
              </span>
              <span className="text-xs uppercase font-extrabold tracking-widest text-slate-400">
                Personal Finance Statement
              </span>
            </div>
            <h1 className="text-2xl sm:text-3xl font-extrabold text-slate-900 mt-2">
              Monthly Financial Performance Report
            </h1>
            <p className="text-xs text-slate-500 mt-1">
              Generated by Personal Finance Advisor Bot • Powered by AI Analysis
            </p>
          </div>

          <div className="text-left sm:text-right text-xs text-slate-500 space-y-1">
            <div>
              <span className="text-slate-400">Account Owner: </span>
              <strong className="text-slate-900">{persona.name}</strong>
            </div>
            <div>
              <span className="text-slate-400">Profile: </span>
              <span className="font-medium text-slate-800">{persona.roleTitle}</span>
            </div>
            <div>
              <span className="text-slate-400">Statement Period: </span>
              <span className="font-semibold text-slate-900">September 2026</span>
            </div>
            <div>
              <span className="text-slate-400">Financial Health: </span>
              <span className="font-bold text-emerald-700">
                {analysis.healthScore}/100 ({analysis.status})
              </span>
            </div>
          </div>
        </div>

        {/* Executive Summary Metrics */}
        <div>
          <h3 className="text-xs font-bold uppercase tracking-wider text-slate-400 mb-3">
            1. Executive Cash Flow Summary
          </h3>
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
            <div className="p-4 rounded-xl border border-slate-200 bg-slate-50">
              <span className="text-[11px] font-semibold text-slate-500 uppercase">
                Total Monthly Inflow
              </span>
              <div className="text-xl font-bold text-slate-900 mt-1">
                {formatCurrency(snapshot.totalIncome, currency)}
              </div>
              <span className="text-[10px] text-slate-400">
                {incomes.length} income source{incomes.length === 1 ? '' : 's'}
              </span>
            </div>

            <div className="p-4 rounded-xl border border-slate-200 bg-slate-50">
              <span className="text-[11px] font-semibold text-slate-500 uppercase">
                Total Outflow
              </span>
              <div className="text-xl font-bold text-slate-900 mt-1">
                {formatCurrency(snapshot.totalExpenses, currency)}
              </div>
              <span className="text-[10px] text-slate-400">
                {expenses.length} logged expense{expenses.length === 1 ? '' : 's'}
              </span>
            </div>

            <div className="p-4 rounded-xl border border-slate-200 bg-slate-50">
              <span className="text-[11px] font-semibold text-slate-500 uppercase">
                Net Savings Achieved
              </span>
              <div
                className={`text-xl font-bold mt-1 ${
                  snapshot.netCashFlow >= 0 ? 'text-emerald-700' : 'text-rose-600'
                }`}
              >
                {snapshot.netCashFlow >= 0 ? '+' : ''}
                {formatCurrency(snapshot.netCashFlow, currency)}
              </div>
              <span className="text-[10px] text-slate-400">Unallocated surplus buffer</span>
            </div>

            <div className="p-4 rounded-xl border border-slate-200 bg-slate-50">
              <span className="text-[11px] font-semibold text-slate-500 uppercase">
                Savings Rate
              </span>
              <div className="text-xl font-bold text-indigo-700 mt-1">
                {snapshot.savingsRate.toFixed(1)}%
              </div>
              <span className="text-[10px] text-slate-400">
                Target: {persona.typicalSavingsPercent}%
              </span>
            </div>
          </div>
        </div>

        {/* AI Diagnostic Commentary */}
        <div className="p-5 rounded-2xl bg-indigo-50/60 border border-indigo-100">
          <div className="flex items-center space-x-2 text-xs font-bold text-indigo-900 uppercase tracking-wider mb-1.5">
            <Bot className="w-4 h-4 text-indigo-600" />
            <span>AI Advisor Diagnostic Synthesis</span>
          </div>
          <p className="text-sm text-slate-800 leading-relaxed font-medium">
            {analysis.summary}
          </p>
        </div>

        {/* Category Budget Breakdown Table */}
        <div>
          <h3 className="text-xs font-bold uppercase tracking-wider text-slate-400 mb-3">
            2. Category Budget & Expense Variance
          </h3>
          <div className="border border-slate-200 rounded-xl overflow-hidden">
            <table className="w-full text-left text-xs">
              <thead className="bg-slate-50 border-b border-slate-200 font-semibold text-slate-600 uppercase">
                <tr>
                  <th className="py-2.5 px-3">Category</th>
                  <th className="py-2.5 px-3">Classification</th>
                  <th className="py-2.5 px-3 text-right">Limit</th>
                  <th className="py-2.5 px-3 text-right">Actual Spent</th>
                  <th className="py-2.5 px-3 text-right">Variance</th>
                  <th className="py-2.5 px-3 text-right">Adherence</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100">
                {(Object.entries(snapshot.categoryTotals) as [ExpenseCategory, number][])
                  .filter(([_, spent]) => spent > 0)
                  .map(([cat, spent]) => {
                    const limit = snapshot.categoryLimits[cat] || 0;
                    const meta = CATEGORIES_CONFIG[cat];
                    const variance = spent - limit;
                    const isOver = limit > 0 && variance > 0;
                    const percent = limit > 0 ? Math.round((spent / limit) * 100) : 100;

                    return (
                      <tr key={cat} className={isOver ? 'bg-rose-50/30' : ''}>
                        <td className="py-2.5 px-3 font-semibold text-slate-900">{cat}</td>
                        <td className="py-2.5 px-3 capitalize text-slate-500">
                          {meta?.classification || 'wants'}
                        </td>
                        <td className="py-2.5 px-3 text-right text-slate-600">
                          {formatCurrency(limit, currency)}
                        </td>
                        <td className="py-2.5 px-3 text-right font-bold text-slate-900">
                          {formatCurrency(spent, currency)}
                        </td>
                        <td
                          className={`py-2.5 px-3 text-right font-bold ${
                            isOver ? 'text-rose-600' : 'text-emerald-700'
                          }`}
                        >
                          {isOver
                            ? `+${formatCurrency(variance, currency)} (Over)`
                            : `-${formatCurrency(Math.abs(variance), currency)}`}
                        </td>
                        <td className="py-2.5 px-3 text-right font-semibold text-slate-700">
                          {percent}%
                        </td>
                      </tr>
                    );
                  })}
              </tbody>
            </table>
          </div>
        </div>

        {/* Savings Goals Status */}
        <div>
          <h3 className="text-xs font-bold uppercase tracking-wider text-slate-400 mb-3">
            3. Savings Goals Progress & Projections
          </h3>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
            {snapshot.savingsGoals.map((g) => {
              const percent = Math.min(100, Math.round((g.currentAmount / g.targetAmount) * 100));
              return (
                <div key={g.id} className="p-3.5 rounded-xl border border-slate-200 text-xs">
                  <div className="flex items-center justify-between font-bold text-slate-900">
                    <span>{g.title}</span>
                    <span className="text-emerald-700">{percent}%</span>
                  </div>
                  <div className="mt-1 flex items-baseline justify-between text-slate-600">
                    <span>Current: {formatCurrency(g.currentAmount, currency)}</span>
                    <span>Target: {formatCurrency(g.targetAmount, currency)}</span>
                  </div>
                  <div className="mt-2 w-full h-1.5 bg-slate-100 rounded-full overflow-hidden">
                    <div
                      className="h-full bg-emerald-500 rounded-full"
                      style={{ width: `${percent}%` }}
                    />
                  </div>
                </div>
              );
            })}
          </div>
        </div>

        {/* Actionable Next Month Remediation Plan */}
        <div>
          <h3 className="text-xs font-bold uppercase tracking-wider text-slate-400 mb-3">
            4. Recommended Financial Action Plan for Next Month
          </h3>
          <div className="space-y-2">
            {analysis.actionableTips.map((tip, idx) => (
              <div
                key={idx}
                className="flex items-start space-x-2 text-xs text-slate-700 p-2.5 bg-slate-50 rounded-lg border border-slate-100"
              >
                <CheckCircle2 className="w-4 h-4 text-emerald-600 shrink-0 mt-0.5" />
                <span className="font-medium">{tip}</span>
              </div>
            ))}
          </div>
        </div>

        {/* Statement Footer */}
        <div className="pt-6 border-t border-slate-200 text-center text-[11px] text-slate-400 space-y-1">
          <p>This statement is generated for personal budgeting and planning purposes.</p>
          <p>Personal Finance Advisor Bot • Autonomous AI Financial Assistant</p>
        </div>
      </div>
    </div>
  );
};
